-- Xóa các bảng theo thứ tự phụ thuộc
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS DANHGIA;
DROP TABLE IF EXISTS THAMGIA;
DROP TABLE IF EXISTS HOATDONG;
DROP TABLE IF EXISTS SINHVIEN;
DROP TABLE IF EXISTS TRUONG;
DROP TABLE IF EXISTS AUDIT_LOG;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user;
SET FOREIGN_KEY_CHECKS = 1;

-- Tạo bảng users
CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(10),
    role VARCHAR(20),
    enabled BOOLEAN DEFAULT true,
    avatar_url VARCHAR(255),
    last_login TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_username (username),
    UNIQUE KEY uk_users_email (email)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

-- Thêm tài khoản admin mặc định (password: admin123)
INSERT INTO users (username, password, email, full_name, role, enabled)
VALUES ('admin', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW', 'admin@localhost', 'Administrator', 'ROLE_ADMIN', true);

-- Tạo bảng AUDIT_LOG
CREATE TABLE AUDIT_LOG (
    Id BIGINT NOT NULL AUTO_INCREMENT,
    Username VARCHAR(50),
    Action VARCHAR(100),
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Details TEXT,
    PRIMARY KEY (Id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

-- Tạo bảng TRUONG
CREATE TABLE TRUONG (
    MaTruong VARCHAR(20) NOT NULL,
    TenTruong VARCHAR(100) NOT NULL,
    DiaChi TEXT,
    KhuVuc VARCHAR(50),
    PRIMARY KEY (MaTruong)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tạo bảng SINHVIEN
CREATE TABLE SINHVIEN (
    MSSV VARCHAR(20) NOT NULL,
    HoTen VARCHAR(100) NOT NULL,
    Email VARCHAR(100),
    SoDT VARCHAR(15),
    Lop VARCHAR(20),
    Khoa VARCHAR(50),
    MaTruong VARCHAR(20),
    PRIMARY KEY (MSSV),
    FOREIGN KEY (MaTruong) REFERENCES TRUONG(MaTruong)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tạo bảng HOATDONG
CREATE TABLE HOATDONG (
    MaHD VARCHAR(20) NOT NULL,
    TenHD VARCHAR(200) NOT NULL,
    MoTa TEXT,
    ThoiGianBatDau TIMESTAMP,
    ThoiGianKetThuc TIMESTAMP,
    DiaDiem TEXT,
    MaToChuc VARCHAR(20),
    PRIMARY KEY (MaHD),
    FOREIGN KEY (MaToChuc) REFERENCES TOCHUC(MaToChuc)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tạo bảng THAMGIA
CREATE TABLE THAMGIA (
    MSSV VARCHAR(20) NOT NULL,
    MaHD VARCHAR(20) NOT NULL,
    ThoiGianThamGia TIMESTAMP,
    SoGioThamGia INT,
    XepLoai VARCHAR(20),
    ChungNhan VARCHAR(255),
    TrangThai VARCHAR(20),
    PRIMARY KEY (MSSV, MaHD),
    FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV),
    FOREIGN KEY (MaHD) REFERENCES HOATDONG(MaHD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tạo bảng DANHGIA
CREATE TABLE DANHGIA (
    MSSV VARCHAR(20) NOT NULL,
    MaHD VARCHAR(20) NOT NULL,
    Diem INT,
    NhanXet TEXT,
    PRIMARY KEY (MSSV, MaHD),
    FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV),
    FOREIGN KEY (MaHD) REFERENCES HOATDONG(MaHD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 